/********************************************************** 
   This file was generated automatically: DO NOT MODIFY

    This source file is part of the user-code that
    implements a Taste function block component generated
    with the ESROCOS robot modeling tool.

  
  Delivered by: KU Leuven, Belgium, 2018
  Generated on: Fri Apr  6 15:44:44 2018 (UTC)
  Generated by: Enea Scioni
  License:      BSD2-clause

**********************************************************/

#include "kinblock.h"

/* This should be placed in the source folder of the target functionblock */
#include "kinblock-bridge.h"

void kinblock_startup()
{
  load_model_constants();
}

void fk1_PI_req(const asn1SccJointState *IN_joints, asn1SccPose *outval_1)
{
  solver_fk1(IN_joints,outval_1);
}

void fk2_PI_req(const asn1SccJointState *IN_joints, asn1SccPose *outval_1)
{
  solver_fk2(IN_joints,outval_1);
}

void ik1_PI_req(const asn1SccJointState *IN_q, const asn1SccVector3d *IN_vector, asn1SccJointState *OUT_qd_ik)
{
  solver_ik1(IN_q, IN_vector,OUT_qd_ik);
}

void ik2_PI_req(const asn1SccVector3d *IN_position, const asn1SccJointState*IN_orientation, asn1SccJointState*IN_guess, asn1SccJointState *OUT_q_ik)
{
  solver_ik2(IN_position, IN_orientation, IN_guess,OUT_q_ik);
}

