/********************************************************** 
   This file was generated automatically: DO NOT MODIFY

    This source file is part of the user-code that
    implements a Taste function block component generated
    with the ESROCOS robot modeling tool.
    It implements the event-loop around the call
    of the solver code.

  
  Delivered by: KU Leuven, Belgium, 2018
  Generated on: Fri Apr  6 15:44:44 2018 (UTC)
  Generated by: Enea Scioni
  License:      BSD2-clause

**********************************************************/

#include "ur5.h"
#include "kinblock-bridge.h"

ur5::mc_config mc;

void load_model_constants() {
    // initialize model constants
}


int solver_fk1(const asn1SccJointState *IN_joints, asn1SccPose *outval_1) {
  ur5::joint_state input; kul::pose_t output_1; ur5::Jacobian_t output_2; ur5::Jacobian_t output_3; 
  // TODO: CONVERT FROM ASN1 TO SOLVER INPUT
  fk1(mc,input,output_1,output_2,output_3);
  // TODO: CONVERT SOLVER OUTPUT TO ASN1
  return 0;
}


int solver_fk2(const asn1SccJointState *IN_joints, asn1SccPose *outval_1) {
  ur5::joint_state input; kul::pose_t output_1; 
  // TODO: CONVERT FROM ASN1 TO SOLVER INPUT
  fk2(mc,input,output_1);
  // TODO: CONVERT SOLVER OUTPUT TO ASN1
  return 0;
}


int solver_ik1(const asn1SccJointState *IN_q, const asn1SccVector3d *IN_vector, asn1SccJointState *OUT_qd_ik) {
  ur5::joint_state q; kul::vector3_t vector; ur5::joint_state qd_ik; 
  // TODO: CONVERT FROM ASN1 TO SOLVER INPUT
  ik1(mc,q, vector, qd_ik);
  // TODO: CONVERT SOLVER OUTPUT TO ASN1
  return 0;
}


int solver_ik2(const asn1SccVector3d *IN_position, const asn1SccJointState*IN_orientation, asn1SccJointState*IN_guess, asn1SccJointState *OUT_q_ik) {
  kul::ik_pos_cfg cfg; kul::vector3_t desired_position; kul::rot_m_t desired_orientation; ur5::joint_state q_guess; ur5::joint_state q_ik; kul::ik_pos_dbg dbg; 
  // TODO: CONVERT FROM ASN1 TO SOLVER INPUT
  ik2(mc,cfg, desired_position, desired_orientation, q_guess, q_ik, dbg);
  // TODO: CONVERT SOLVER OUTPUT TO ASN1
  return 0;
}

